### ISSUE TITLE
Encoder values update rate

### ISSUE THREAD

**Issue by bcm0** [Scheik/md49_base_controller#1]
I try launching your example:
roslaunch base_controller base_controller_remote.launch
roslaunch robot_teleop joystick_driver.launch
roslaunch base_odometry base_odometry.launch
roslaunch robot_urdf robot_rviz.launch
In addition I run "rostopic echo md49_encoders".

The "encoder_l" and "encoder_r" values have a very low refresh rate although the "seq:" counter runs smoothly . As a result the robot does not drive smoothly in rviz.
Do you have an idea?

**Comment by Scheik** [comment]
Does the robot just not drive smoothly in rviz (so visualization is stuttering) or also in reallity?

I haven't had that problem, visualization ran smooth. What rate do you run the serial communication with the MD49 9600 or 38400 bps?

ROS loop rate for the basecontroller is at 10Hz, not the very fastest, maybe you can increase that value in the sourcefile:  _md49_base_controller_node.cpp_

May I have more information of your project? Pictures/ Own documentation and so on? I am very happy that someone uses my sources and would be really interested in your own project. Do you know my [project-documentation](http://www.the-starbearer.de/)?

**Comment by bcm0** [comment]
Could be a problem with the voltage divider...
Reducing Baudrate sometimes solves it. Thank you!

**Comment by adnion** [comment]
Partly found the problem myself.
It's a huge difference if I run md49_base_controller remotely or locally. It only works locally.
Additionally I set the update rate to 100Hz. Thank you for the tip!
