### ISSUE TITLE
Where I put the dimension of the mobile robot?

### ISSUE THREAD

**Issue by Desoky01** [Scheik/md49_base_controller#2]
Hi:
I have two questions; 
the first one is :
This package is used to transform the linear and angular velocities to left and right wheels speed.
How the package do the transformation without the dimension of the mobile robot? according to the following equations:
omega_l=(2* Linear velocity +angular velocity * robot width)/ (2*wheel radius)
omega_r=(2*  Linear velocity -angular velocity * robot width)/ (2*wheel radius)

the second one is:
the package is used Linear velocity=vel_cmd.linear.x  >>> I think  it is wrong.
the right is 
Linear velocity=sqrt(vel_cmd.linear.x^2+vel_cmd.linear.y^2)

**Comment by Scheik** [comment]
The package itself is not meant to compute odometry. It's just meant as bare driver for the MD49 board and drives. My approach of a base_odometry node you can find here:
https://github.com/Scheik/ROS-Workspace/tree/master/src/base_odometry
